# meta-hello-overlay/recipes-bsp/bootfiles/rpi-config_git.bbappend

# Add extra lines at the end of config.txt generated by rpi-config
# The leading "\n" ensures we start on a new line.
RPI_EXTRA_CONFIG:append = "\n# Enable custom hello-led overlay\ndtoverlay=hello-led\n"
